// Renders three sample pages FROM THE REAL BUILDERS, so review reflects what the
// product actually emits. Run: npx tsx scripts/seo/sample-pages.mts > /tmp/samples.json
//
// Study and Jobs are generated by buildStudyPage/buildJobsPage against real axis
// rows. The naturalisation page is a static component, so its own module is the
// source: its facts live in their own module (facts.ts) precisely so a script can
// import exactly what ships rather than a transcription of it.

import { buildStudyPage, buildJobsPage } from "../../src/lib/seo/content";
import { COUNTRIES, UNIVERSITIES, SUBJECTS, ROLES, HUBS } from "../../src/lib/seo/axes";
import { resolveOriginBlock } from "../../src/lib/seo/origin-localization";
import { KNOWN, UNKNOWN, FAQ } from "../../src/app/swiss-naturalisation-language/facts";

const pick = <T,>(arr: T[], pred: (x: T) => boolean, label: string): T => {
  const hit = arr.find(pred);
  if (!hit) throw new Error(`no ${label} matched — axis changed?`);
  return hit;
};

// Deliberate choices, not the first row of each axis:
//  • India → a very high-volume origin, and one where the origin block is localized.
//  • Geneva → FRENCH-speaking. If the jobs page says "German" here, the language axis
//    is broken, and that is the single most likely fork bug in this product.
//  • Nurse → regulated + client-facing, so both conditional branches fire.
const country = pick(COUNTRIES, (c) => c.slug === "india", "country india");
const subject = pick(SUBJECTS, (s) => s.slug === "medicine-health-sciences", "subject medicine");
const uni = pick(UNIVERSITIES, (u) => u.countryName === "India" && u.subjects.length > 0, "an Indian university");
const role = pick(ROLES, (r) => /nurse/i.test(r.name), "role nurse");
const geneva = pick(HUBS, (h) => h.slug === "geneva", "hub geneva");
const zurich = pick(HUBS, (h) => h.slug === "zurich", "hub zurich");

const origin = resolveOriginBlock(country);

const out = {
  study: buildStudyPage(subject, country, uni, origin),
  jobsGeneva: buildJobsPage(role, country, geneva, origin),
  jobsZurich: buildJobsPage(role, country, zurich, origin),
  naturalisation: { known: KNOWN, unknown: UNKNOWN, faq: FAQ },
  meta: {
    country: country.name,
    subject: subject.name,
    uni: `${uni.name} (${uni.city})`,
    role: role.name,
    hubs: [`${geneva.name} — ${geneva.region}`, `${zurich.name} — ${zurich.region}`],
  },
};

console.log(JSON.stringify(out, null, 2));
